### ISSUE TITLE
No Momentum When Jumping

### ISSUE THREAD

**Issue by Chi-Ling** [EliTheCoder/synergy#2]
A good idea for fixing this would be a script that basically says if ob. in air and direction was pressed during the jump, continue it's trajectory until it touches the ground again, then use regular physics, unless acted upon by another command in the air.

**Comment by Chi-Ling** [comment]
It's not the best idea, but maybe it could work

**Comment by EliTheCoder** [comment]
Alright, this has been added in an update a couple days ago. The way it works is, there is no friction while you are in the air. The friction part of the code doesn't run unless your y = 0 or you are stacked on top of a block
